name: pull-request-changes

on: 
  pull_request:
    branches: [main]
env:
    ORGANIZATION: 'enrico23'
    REPOSITORY: 'DeploymentTestApp'
    MY_GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    DOTNET_VERSION: '6.0.x'
    BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration

jobs:
  get-pr-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: Bhacaz/checkout-files@v2
      with:
         files: tools

    - name: Get PR changes
      id: GetPrChanges
      shell: pwsh
      run: |
        echo "Get Pull Request changes"
        $files= $(gh api repos/${{ env.ORGANIZATION }}/${{ env.REPOSITORY }}/pulls/${{ github.event.pull_request.number }}/files)
        $usersObject = ConvertFrom-Json –InputObject $files
        $changedFiles = $usersObject | select -ExpandProperty filename
        echo $changedFiles > pull-request-changes.txt
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: pull-request-changes
          path: pull-request-changes.txt
          if-no-files-found: warn