name: pull-request-changes

on: 
  pull_request:
    branches: [main]
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-pr-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR changes
      id: GetPrChanges
      shell: pwsh
      run: |
        echo "Get Pull Request changes"
        $files= $(gh api repos/enrico23/DeploymentTestApp/pulls/${{ github.event.pull_request.number }}/files)
        echo $files
        $usersObject = ConvertFrom-Json –InputObject $files
        $changedFiles = $usersObject | select -ExpandProperty filename
        echo $changedFiles
        echo $files > pull-request-changes.txt
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: pull-request-changes
          path: pull-request-changes.txt
          if-no-files-found: warn


