name: pull-request-changes

on: 
  pull_request:
    branches: [main]
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-pr-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR changes
      id: GetPrChanges
      shell: pwsh
      run: |
        echo ::set-output name=files::$(gh api repos/enrico23/DeploymentTestApp/pulls/${{ github.event.pull_request.number }}/files)
        # The API returns a non-terminating error and the GH workflows are presetting non-terminating
        # errors to terminating.
        continue-on-error: true

        echo "hello hello"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: pull-request-changes
          path: pull-request-changes.txt
            


